vich_uploader:
    db_driver: orm

    mappings:
        person_images:
            uri_prefix: /images/person
            upload_destination: '%kernel.project_dir%/public/images/person'


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
