vich_uploader:
    db_driver: orm

    mappings:
        movie_images:
            uri_prefix: /images/movies
            upload_destination: '%kernel.project_dir%/public/images/movies'


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
